### ISSUE TITLE
how to create a user for Gerrit or Redmine?

### ISSUE THREAD

**Issue by ghost** [openfrontier/ci#7]
> Gerrit and Redmine share the same LDAP authentication system which is specified in the config file. ->So you are able to use the same username and password to log in those systems.
> In this authentication mode, how to create a user for Gerrit or Redmine?

**Comment by thinkernel** [comment]
There are two options.
1. Add users by editing the ~/openldap-docker/base.ldif file. Then execute `docker exec openldap ldapadd -f /base.ldif -x -D "cn=admin,dc=example,dc=com" -w secret`. Then execute `docker exec openldap ldappasswd` to change the password. This is not a convenient way. So I offer you another option.
2. Use some ldap client tools like ldapadmin or phpldapadmin to connect to the openldap container and  manage it by using your favorite tools. You may even deploy a phpldapadmin docker container in your server.

**Comment by ghost** [comment]
cp base.ldif gerrit.dev.ldff
vi gerrit.dev.ldff 
#####################
dn: ou=gerrit,dc=example,dc=com
objectClass: organizationalUnit
ou: gerrit
description: All groups of gerrit.

dn: ou=accounts,dc=example,dc=com
objectClass: organizationalUnit
ou: accounts
description: All accounts' entries are under this group.

dn: cn=group,ou=accounts,dc=example,dc=com
objectClass: posixGroup
cn: group
description: group
gidNumber: 10000

dn: uid=dev,ou=accounts,dc=example,dc=com
objectClass: posixAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
homeDirectory: **/home/dev**
loginShell: /bin/false
gidNumber: 10000
uid: **dev**
cn: **gerrit dev**
displayName: **gerrit dev**
uidNumber: **10001**
sn: **dev**
givenName: gerrit
mail: **gerrit.dev@example.com**
###############################

**# docker exec openldap ldapadd -f /gerrit.dev.ldff -x -D "cn=dev,dc=example,dc=com" -w secret
ldap_bind: Invalid credentials (49)**

so What am I to do?

**Comment by ghost** [comment]
In addition, I would like to use the openid authentication mode, how do I modify files?

**Comment by thinkernel** [comment]
The default administrator credentials of ldap should be `cn=admin,dc=example,dc=com`.
So, `-D cn=admin,dc=example,dc=com` might be the correct one.
The AUTH_TYPE of OAUTH/LDAP/DEVELOPMENT_BECOME_ANY_ACCOUNT are supported. Check this [README](https://github.com/openfrontier/docker-gerrit/blob/master/README.md), please. OpenID is not supported yet. Feel free to make it support openid by hacking [this file](https://github.com/openfrontier/docker-gerrit/blob/master/gerrit-entrypoint.sh). I would be very happy to accept a pull request like that.

**Comment by ghost** [comment]
I want to create a common user. Not administrator.
So how am I going to do it?

################################
dn: uid=dev,ou=accounts,dc=hpe,dc=com
displayName: gerrit dev
userPassword: {SSHA}+/A0M0DM7YjPoo304akgibSQHj4ZyVDh
givenName: gerrit
uidNumber: 10001
uid: dev
loginShell: /bin/false
sn: dev
gidNumber: 10000
mail: dev@hpe.com
cn: gerrit dev
homeDirectory: /home/gerrit
objectClass: posixAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
################################
Error: LDAPException: Insufficient Access Rights (50) Insufficient Access Rights
LDAPException: Server Message: no write access to parent

**Comment by thinkernel** [comment]
[LdapAdmin](http://www.ldapadmin.org/) might be a good choice.
It's a Windows LDAP client. I use it myself.

**Comment by Fred-cai** [comment]
General					
	Connetction				
		Host:192.168.221.171	Port:	389
		Base:dc=example,dc=com	
		Simple authentication			
Account					
	Username:uid=admin,ou=accounts,dc=example,dc=com			
	Passwd:passwd			
I can connectted,but I can not create new user.
############################################
LDAPException: Server Message: no write access to parent
############################################
Can you tell me where it is wrong?

**Comment by ghost** [comment]
it is ok.thank you very much.
