### ISSUE TITLE
cannot login in gerrit  with admin account

### ISSUE THREAD

**Issue by inking007** [openfrontier/ci#8]
when I try to connect and login gerrit web . I met following error.

"Authentication unavailable at this time."

I used ldap container of  openfrontier and didn't change any configuration.

**Comment by thinkernel** [comment]
The `HOST_NAME` in`ci/config` is supposed to be changed to your server's IP address of FQDN. Otherwise,  gerrit container will connect Ldap container through 127.0.0.1 which is unavailable.

**Comment by inking007** [comment]
I solved the problem due to your advice.
thank you

**Comment by thinkernel** [comment]
No problem. Have fun.
